# Generated by Django 4.1 on 2025-04-21 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 14, 1, 31, 351363), verbose_name='Дата создания'),
        ),
    ]
