# Generated by Django 4.1 on 2025-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'role_type', 'content_type', 'object_id')},
        ),
    ]
