export const mockRequests = [
    {
      id: 1,
      name: 'Смирнова Анна Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'ЛК стажера',
      project: 'Разработка CRM-системы',
      specialization: 'Фронтенд',
      testScore: 85,
      institution: 'МГТУ имени Баумана',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 2,
      name: 'Петров Иван Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'Игры',
      project: 'Создание игрового прототипа',
      specialization: 'Дизайн',
      testScore: 90,
      institution: 'НИУ ВШЭ',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 3,
      name: 'Кузнецова Мария Петровна',
      status: 'Приступившие к работе',
      eventName: 'Осенний марафон',
      direction: '1С',
      project: 'Автоматизация складов',
      specialization: 'Аналитика',
      testScore: 75,
      institution: 'СПбГУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 4,
      name: 'Орлов Дмитрий Петрович',
      status: 'Новые заявки',
      eventName: 'Киберспортивный турнир',
      direction: 'Игры',
      project: 'Проектирование уровней',
      specialization: 'Дизайн',
      testScore: 82,
      institution: 'МГИМО',
      course: 1,
      description: "Тырым пырым",
    },
    {
      id: 5,
      name: 'Воронова Екатерина Петровна',
      status: 'Вступившие в орг. чат',
      eventName: 'Летняя школа',
      direction: 'ЛК стажера',
      project: 'Образовательная платформа',
      specialization: 'Фронтенд',
      testScore: 88,
      institution: 'УрФУ',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 6,
      name: 'Васильев Алексей Петрович',
      status: 'Приступившие к работе',
      eventName: 'Зимняя школа',
      direction: '1С',
      project: 'Учет финансов',
      specialization: 'Аналитика',
      testScore: 92,
      institution: 'КФУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 7,
      name: 'Соколова Ольга Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'Игры',
      project: 'Разработка сценариев',
      specialization: 'Дизайн',
      testScore: 78,
      institution: 'МФТИ',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 8,
      name: 'Васильев Николай Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'ЛК стажера',
      project: 'Создание CMS',
      specialization: 'Фронтенд',
      testScore: 84,
      institution: 'МИСиС',
      course: 3,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc",
    },
    {
      id: 9,
      name: 'Смирнова Анна Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'ЛК стажера',
      project: 'Разработка CRM-системы',
      specialization: 'Фронтенд',
      testScore: 85,
      institution: 'МГТУ имени Баумана',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 10,
      name: 'Петров Иван Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'Игры',
      project: 'Создание игрового прототипа',
      specialization: 'Дизайн',
      testScore: 90,
      institution: 'НИУ ВШЭ',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 11,
      name: 'Кузнецова Мария Петровна',
      status: 'Приступившие к работе',
      eventName: 'Осенний марафон',
      direction: '1С',
      project: 'Автоматизация складов',
      specialization: 'Аналитика',
      testScore: 75,
      institution: 'СПбГУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 12,
      name: 'Орлов Дмитрий Петрович',
      status: 'Новые заявки',
      eventName: 'Киберспортивный турнир',
      direction: 'Игры',
      project: 'Проектирование уровней',
      specialization: 'Дизайн',
      testScore: 82,
      institution: 'МГИМО',
      course: 1,
      description: "Тырым пырым",
    },
    {
      id: 13,
      name: 'Воронова Екатерина Петровна',
      status: 'Вступившие в орг. чат',
      eventName: 'Летняя школа',
      direction: 'ЛК стажера',
      project: 'Образовательная платформа',
      specialization: 'Фронтенд',
      testScore: 88,
      institution: 'УрФУ',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 14,
      name: 'Васильев Алексей Петрович',
      status: 'Приступившие к работе',
      eventName: 'Зимняя школа',
      direction: '1С',
      project: 'Учет финансов',
      specialization: 'Аналитика',
      testScore: 92,
      institution: 'КФУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 15,
      name: 'Соколова Ольга Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'Игры',
      project: 'Разработка сценариев',
      specialization: 'Дизайн',
      testScore: 78,
      institution: 'МФТИ',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 16,
      name: 'Васильев Николай Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'ЛК стажера',
      project: 'Создание CMS',
      specialization: 'Фронтенд',
      testScore: 84,
      institution: 'МИСиС',
      course: 3,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc",
    },
    {
      id: 17,
      name: 'Смирнова Анна Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'ЛК стажера',
      project: 'Разработка CRM-системы',
      specialization: 'Фронтенд',
      testScore: 85,
      institution: 'МГТУ имени Баумана',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 18,
      name: 'Петров Иван Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'Игры',
      project: 'Создание игрового прототипа',
      specialization: 'Дизайн',
      testScore: 90,
      institution: 'НИУ ВШЭ',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 19,
      name: 'Кузнецова Мария Петровна',
      status: 'Приступившие к работе',
      eventName: 'Осенний марафон',
      direction: '1С',
      project: 'Автоматизация складов',
      specialization: 'Аналитика',
      testScore: 75,
      institution: 'СПбГУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 20,
      name: 'Орлов Дмитрий Петрович',
      status: 'Новые заявки',
      eventName: 'Киберспортивный турнир',
      direction: 'Игры',
      project: 'Проектирование уровней',
      specialization: 'Дизайн',
      testScore: 82,
      institution: 'МГИМО',
      course: 1,
      description: "Тырым пырым",
    },
    {
      id: 21,
      name: 'Воронова Екатерина Петровна',
      status: 'Вступившие в орг. чат',
      eventName: 'Летняя школа',
      direction: 'ЛК стажера',
      project: 'Образовательная платформа',
      specialization: 'Фронтенд',
      testScore: 88,
      institution: 'УрФУ',
      course: 3,
      description: "Тырым пырым",
    },
    {
      id: 22,
      name: 'Васильев Алексей Петрович',
      status: 'Приступившие к работе',
      eventName: 'Зимняя школа',
      direction: '1С',
      project: 'Учет финансов',
      specialization: 'Аналитика',
      testScore: 92,
      institution: 'КФУ',
      course: 4,
      description: "Тырым пырым",
    },
    {
      id: 23,
      name: 'Соколова Ольга Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'Игры',
      project: 'Разработка сценариев',
      specialization: 'Дизайн',
      testScore: 78,
      institution: 'Федеральное государственное автономное образовательное учреждение высшего образования «Национальный исследовательский технологический университет МИСИС»',
      course: 2,
      description: "Тырым пырым",
    },
    {
      id: 24,
      name: 'Васильев Николай Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'ЛК стажера',
      project: 'Создание CMS',
      specialization: 'Фронтенд',
      testScore: 84,
      institution: 'Федеральное государственное автономное образовательное учреждение высшего образования «Национальный исследовательский технологический университет МИСИС»',
      course: 3,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc",
    },
];