export const mockRequests = [
    {
      id: 1,
      name: 'Смирнова Анна Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'ЛК стажера',
      project: 'Разработка CRM-системы',
      specialization: 'Фронтенд',
      testScore: 85,
      institution: 'МГТУ имени Баумана',
      course: 3,
    },
    {
      id: 2,
      name: 'Петров Иван Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'Игры',
      project: 'Создание игрового прототипа',
      specialization: 'Дизайн',
      testScore: 90,
      institution: 'НИУ ВШЭ',
      course: 2,
    },
    {
      id: 3,
      name: 'Кузнецова Мария Петровна',
      status: 'Приступившие к работе',
      eventName: 'Осенний марафон',
      direction: '1С',
      project: 'Автоматизация складов',
      specialization: 'Аналитика',
      testScore: 75,
      institution: 'СПбГУ',
      course: 4,
    },
    {
      id: 4,
      name: 'Дмитрий Орлов Петрович',
      status: 'Новые заявки',
      eventName: 'Киберспортивный турнир',
      direction: 'Игры',
      project: 'Проектирование уровней',
      specialization: 'Дизайн',
      testScore: 82,
      institution: 'МГИМО',
      course: 1,
    },
    {
      id: 5,
      name: 'Воронова Екатерина Петровна',
      status: 'Вступившие в орг. чат',
      eventName: 'Летняя школа',
      direction: 'ЛК стажера',
      project: 'Образовательная платформа',
      specialization: 'Фронтенд',
      testScore: 88,
      institution: 'УрФУ',
      course: 3,
    },
    {
      id: 6,
      name: 'Васильев Алексей Петрович',
      status: 'Приступившие к работе',
      eventName: 'Зимняя школа',
      direction: '1С',
      project: 'Учет финансов',
      specialization: 'Аналитика',
      testScore: 92,
      institution: 'КФУ',
      course: 4,
    },
    {
      id: 7,
      name: 'Соколова Ольга Петровна',
      status: 'Новые заявки',
      eventName: 'Хакатон 2024',
      direction: 'Игры',
      project: 'Разработка сценариев',
      specialization: 'Дизайн',
      testScore: 78,
      institution: 'МФТИ',
      course: 2,
    },
    {
      id: 8,
      name: 'Васильев Николай Петрович',
      status: 'Вступившие в орг. чат',
      eventName: 'Весенний кубок',
      direction: 'ЛК стажера',
      project: 'Создание CMS',
      specialization: 'Фронтенд',
      testScore: 84,
      institution: 'МИСиС',
      course: 3,
    },
];